name: furniture_uikit
description: "App package uikit"
version: 0.0.1
#homepage:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.otf
        #   weight: 700
        # - asset: assets/fonts/Nunito-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/Nunito-Regular.ttf
        #   weight: 400

flutter_gen:
  output: lib/src/assets/
  line_length: 100

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: FurnitureAssets

  integrations:
    flutter_svg: true
